spring.application.name=bff-agendador-tarefas

usuario.url=http://localhost:8080/usuario
agendador-tarefas.url=http://localhost:8081/tarefas
notificacao.url=http://localhost:8082

server.port=8083

spring.cloud.openfeign.httpclient.hc5.enabled=true


cron.horario=0 0/1 * * * ?

usuario.email=admin@admin.com
usuario.senha=1234